// Code generated by goctl. DO NOT EDIT!
// Source: finger-go.proto

package g2

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	G2 interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultG2 struct {
		cli zrpc.Client
	}
)

func NewG2(cli zrpc.Client) G2 {
	return &defaultG2{
		cli: cli,
	}
}

func (m *defaultG2) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := NewG2Client(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
