// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: finger-go.proto

package g2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// G2Client is the client API for G2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type G2Client interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type g2Client struct {
	cc grpc.ClientConnInterface
}

func NewG2Client(cc grpc.ClientConnInterface) G2Client {
	return &g2Client{cc}
}

func (c *g2Client) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/g2.finger-go/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// G2Server is the server API for G2 service.
// All implementations must embed UnimplementedG2Server
// for forward compatibility
type G2Server interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedG2Server()
}

// UnimplementedG2Server must be embedded to have forward compatible implementations.
type UnimplementedG2Server struct {
}

func (UnimplementedG2Server) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedG2Server) mustEmbedUnimplementedG2Server() {}

// UnsafeG2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to G2Server will
// result in compilation errors.
type UnsafeG2Server interface {
	mustEmbedUnimplementedG2Server()
}

func RegisterG2Server(s grpc.ServiceRegistrar, srv G2Server) {
	s.RegisterService(&G2_ServiceDesc, srv)
}

func _G2_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(G2Server).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/g2.finger-go/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(G2Server).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// G2_ServiceDesc is the grpc.ServiceDesc for G2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var G2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "g2.finger-go",
	HandlerType: (*G2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _G2_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finger-go.proto",
}
