// Code generated by goctl. DO NOT EDIT!
// Source: finger-go.proto

package server

import (
	"context"

	"G2/Users/zjc/code/g2"
	"G2/Users/zjc/code/internal/logic"
	"G2/Users/zjc/code/internal/svc"
)

type G2Server struct {
	svcCtx *svc.ServiceContext
	g2.UnimplementedG2Server
}

func NewG2Server(svcCtx *svc.ServiceContext) *G2Server {
	return &G2Server{
		svcCtx: svcCtx,
	}
}

func (s *G2Server) Ping(ctx context.Context, in *g2.Request) (*g2.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
